---
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: unless-stopped
    ports:
      - 8086:8086
    volumes:
      - /var/lib/influxdb2
      - /etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${DOCKER_INFLUXDB_INIT_USERNAME:-admin}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${DOCKER_INFLUXDB_INIT_PASSWORD:-password}
      - DOCKER_INFLUXDB_INIT_ORG=${DOCKER_INFLUXDB_INIT_ORG:-signalk}
      - DOCKER_INFLUXDB_INIT_BUCKET=${DOCKER_INFLUXDB_INIT_ORG:-signalk}
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    user: 1000:1000
    ports:
      - 3001:3000
    volumes:
      - /var/lib/grafana
    links:
      - influxdb

  signalk:
    image: ghcr.io/signalk/signalk-server:${SIGNALK_VERSION:-latest}
    container_name: signalk-server
    restart: unless-stopped
    ports:
      - 3000:3000
      - 10110:10110
    volumes:
      - ~/.signalk:/home/node/.signalk
      - /var/run/dbus:/var/run/dbus
    # Run as privileged to access bluetooth, etc
    privileged: true

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    ports:
      - 80:3000
    volumes:
      - ./homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock # Enable docker integeration
