---
services:
  # # https://github.com/gethomepage/homepage
  # homepage:
  #   image: ghcr.io/gethomepage/homepage:latest
  #   container_name: homepage
  #   environment:
  #     PUID: 1000 # optional, your user id
  #     PGID: 1000 # optional, your group id
  #   ports:
  #     - 80:3000
  #   volumes:
  #     - /external/data/homepage:/app/config # Make sure your local config directory exists
  #     - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
  #   restart: unless-stopped
  # https://hub.docker.com/r/linuxserver/plex
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - VERSION=docker
      # https://plex.tv/claim (expires within 4 minutes)
      # - PLEX_CLAIM= #optional
    volumes:
      - /external/data/plex:/config
      - /external/media/TV:/tv
      - /external/media/Movies:/movies
      - /dev/dri:/dev/dri # hardware acceleration
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /external/data/sonarr:/config
      - /external/media/TV:/tv #optional
      - /external/downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /external/data/radarr:/config
      - /external/media/Movies:/movies #optional
      - /external/downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /external/data/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
  influxdb:
    image: "influxdb:latest"
    container_name: influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - "/home/pi/influxdb:/var/lib/influxdb2"
      - "/home/pi/influxdb:/etc/influxdb2"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=pi
      - DOCKER_INFLUXDB_INIT_PASSWORD=whatyougiveuptogetit
      - DOCKER_INFLUXDB_INIT_ORG=Ada
      - DOCKER_INFLUXDB_INIT_BUCKET=signalk
  grafana:
    image: "grafana/grafana"
    container_name: grafana
    restart: unless-stopped
    user: 1000:1000
    ports:
      - "3001:3000"
    volumes:
      - /home/pi/grafana:/var/lib/grafana
    links:
      - influxdb
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    ports:
      - 80:3000
    volumes:
      - ./homepage:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      # DNS Ports
      - "53:53/tcp"
      - "53:53/udp"
      # Default HTTP Port
      - "80:80/tcp"
      # Default HTTPs Port. FTL will generate a self-signed certificate
      - "443:443/tcp"
      # Uncomment the below if using Pi-hole as your DHCP Server
      #- "67:67/udp"
    environment:
      # Set the appropriate timezone for your location (https://en.wikipedia.org/wiki/List_of_tz_database_time_zones), e.g:
      TZ: "America/New_York"
      # Set a password to access the web interface. Not setting one will result in a random password being assigned
      FTLCONF_webserver_api_password: "whatyougiveuptogetit"
    # Volumes store your data between container upgrades
    volumes:
      # For persisting Pi-hole's databases and common configuration file
      - "/external/data/pihole:/etc/pihole"
      # Uncomment the below if you have custom dnsmasq config files that you want to persist. Not needed for most starting fresh with Pi-hole v6. If you're upgrading from v5 you and have used this directory before, you should keep it enabled for the first v6 container start to allow for a complete migration. It can be removed afterwards. Needs environment variable FTLCONF_misc_etc_dnsmasq_d: 'true'
      #- './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      # See https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
      # Required if you are using Pi-hole as your DHCP server, else not needed
      - NET_ADMIN
      # Required if you are using Pi-hole as your NTP client to be able to set the host's system time
      - SYS_TIME
      # Optional, if Pi-hole should get some more processing time
      - SYS_NICE
    restart: unless-stopped
