---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Boat:
    - Grafana:
        href: http://pi.local:3001/
        icon: grafana.png
        description: Graphs the boat data
        server: local-docker
        container: grafana
    - Signal K:
        href: http://pi.local:3000/
        icon: http://pi.local:3000/admin/img/favicon.ico
        description: Collects the boat data
    - InfluxDB:
        href: http://pi.local:8086/
        icon: influxdb.png
        description: Stores the boat data
        server: local-docker
        container: influxdb
    - Portainer:
        href: http://pi.local:9000/
        icon: portainer.png
        description: Manage docker containers
        server: local-docker
        container: portainer
