---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Boat:
    - Signal K:
        href: http://{{HOMEPAGE_VAR_HOSTNAME}}:3000/
        icon: http://{{HOMEPAGE_VAR_HOSTNAME}}:3000/admin/img/favicon.ico
        description: Collects the boat data
        server: local-docker
        container: signalk
    - Grafana:
        href: http://{{HOMEPAGE_VAR_HOSTNAME}}:3001/
        icon: grafana.png
        description: Graphs the boat data
        server: local-docker
        container: grafana
    - InfluxDB:
        href: http://{{HOMEPAGE_VAR_HOSTNAME}}:8086/
        icon: influxdb.png
        description: Stores the boat data
        server: local-docker
        container: influxdb
    - Portainer:
        href: http://{{HOMEPAGE_VAR_HOSTNAME}}:9000/
        icon: portainer.png
        description: Manage docker containers
        server: local-docker
        container: portainer
